### ISSUE TITLE
Remove duplicates in public/js/app.js and public/js/add.js

### ISSUE THREAD

**Issue by akiraheid** [akiraheid/recipes#128]
There are duplicate functions defined in `public/js/app.js` and `public/js/add.js`. For example, both define a function `removeElement(1)`.

**Comment by danielmartinezsarta** [comment]
#130

**Comment by bohorquezod** [comment]
Hey, I made a [PR](https://github.com/akiraheid/recipes/pull/133) too, I removed the duplicates from app.js instead of add.js and i included on you appScript.pug file. Take a look 👍
